FiguresMOU
========================================================

```{r , echo=FALSE}
library(knitr)

opts_chunk$set(comment=NA, fig.width =8, 
                           fig.height=6,
                           fig.path  ="../tex/",
                           warning=FALSE, 
                           message=FALSE, 
                           error  =FALSE, 
                           echo   =FALSE,
                           cache  =TRUE)
```


```{r -init}
library(ggplot2)
library(FLCore)
library(FLash)
library(FLBRP)
library(ggplotFL)

dirDat='/home/laurie/MEGAsync/papers/tuna-mse/data'

load(file.path(dirOld,"OMs.RData"))
load(file.path(dirOld,"BRPs.RData"))
```

MOU counterfactual
---------------------------------------
```{r popPar}
load(file.path(dirDat,"design.RData"))
load(file.path(dirDat,"priors.RData"))

library(RSQLite)
library(DBI)

##Data sets
db    =file.path(dirNew,"mou.db")

# FLBRPs and FLStocks based on design
load(file.path(dirNew,"/OMs.RData"))
load(file.path(dirNew,"/BRPs.RData"))
load(file.path(dirNew,"/omKey.RData"))

## OMs & HCRs
options=list(OM =expand.grid(iOM=1:128,ar=c(0.0,0.5)),
             HCR=expand.grid(ftar=seq(0,2.5,0.1)))

scen=expand.grid(iOM=seq(dim(options$OM)[1]),iF=seq(dim(options$HCR)[1]))
scen=with(scen,cbind(options$OM[iOM,],options$HCR[iF,]))

## Years and Iters
start=50; end=150; interval=3; rcvPeriod=3
nits =1000; seed=7890 

## Recruitment residuals
set.seed(seed)
flq=FLQuant(0,dimnames=list(year=1:(end+interval)))
srDev=FLQuants("0"=exp(lh:::noise(nits,flq,b=0,sd=.3)))

set.seed(seed)
srDev[["0.5"]]   =exp(lh:::noise(nits,flq,b=0.3,sd=0.5))

m_ply(scen[,1:3],function(iOM,ar,ftar){
  
  eql=BRPs[[iOM]]
  srD=srDev[[ac(ar)]]

  #### OM
  om =OMs[[iOM]]
  if (dims(om)$maxyear < end+interval)
      om =fwdWindow(om,end=end+interval,eql)
    
  ## F in recovery period
  rcv.=seq(c(fbar(om)[,ac(start)]),c(FLBRP:::refpts(eql)["msy","harvest"])*ftar,
           length.out=rcvPeriod+1)
  rcv =FLQuant(rcv.,dimnames=dimnames(fbar(om)[,ac(start+0:rcvPeriod)]))
  om  =FLash:::fwd(om,f=rcv, sr=eql)
    
  ## F in longterm
  lgt =FLQuant(rcv.[rcvPeriod+1],
                      dimnames=list(year=(start+rcvPeriod+1):(end+interval)))
  om  =FLash:::fwd(om,f=lgt,sr=eql)
    
  ## Add stochastcity
  om  =propagate(om,nits)
  om =FLash:::fwd(om,f =rlnorm(nits,log(fbar(FLCore:::iter(om,1))[,
                                      ac(2:(end+interval))]),0.1),
                     sr=eql,
                     sr.residuals=srD)
  
  #### Save results
  drv=dbDriver("SQLite")
  con=dbConnect(drv, dbname=db)
    
  mou=cbind(OM=iOM,ar=ar,ftar=ftar,tseries(om,eql))

  dbWriteTable(con, "mou", mou,append=TRUE)
  
  dbDisconnect(con)})
```
